require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

